[font]
size = 16.0

[font.normal]
family = "Hack"
style = "Regular"

[font.bold]
family = "Hack"
style = "Bold"

[font.italic]
family = "Hack"
style = "Italic"

[window]
padding = { x = 8, y = 8 }
decorations = "Full"
startup_mode = "Maximized"

[cursor]
style = {shape = "Block", blinking = "On"}

[selection]
save_to_clipboard = true

[bell]
animation = "Ease"
duration = 0
